In [2]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
#loading dataset

df = pd.read_csv('D:\\PROJECTS\\Projects\\creditcardfrauddetection\\fraudTest.csv')

In [5]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [6]:
#dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

In [7]:
#checking the nuber of missing values in each column
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [8]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [9]:
X = df.drop(columns=['is_fraud'])  # Assuming 'is_fraud' is the target variable
y = df['is_fraud']

In [10]:
# Assuming 'date_column' is the column with date/time values
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

df['year'] = df['trans_date_trans_time'].dt.year
df['month'] = df['trans_date_trans_time'].dt.month
df['day'] = df['trans_date_trans_time'].dt.day
df['hour'] = df['trans_date_trans_time'].dt.hour
df['minute'] = df['trans_date_trans_time'].dt.minute

# Now you have separate numeric features for date and time
# Accessing the 'year' column
year_column = df['year']

# Accessing the 'month' column
month_column = df['month']

# Accessing the 'day' column
day_column = df['day']

# Accessing the 'hour' column
hour_column = df['hour']

# Accessing the 'minute' column
minute_column = df['minute']

In [11]:
# Drop the 'date_column' if you haven't already
df = df.drop(columns=['trans_date_trans_time'])

In [12]:
df

,Unnamed: 0,cc_num,merchant,category,amt,first,last,gender,street,city,...,trans_num,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,minute
0,0,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,...,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2020,6,21,12,14
1,1,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,...,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,2020,6,21,12,14
2,2,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,...,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0,2020,6,21,12,14
3,3,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,...,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0,2020,6,21,12,15
4,4,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,...,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0,2020,6,21,12,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,2020,12,31,23,59
555715,555715,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,2020,12,31,23,59
555716,555716,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,2020,12,31,23,59
555717,555717,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,2020,12,31,23,59
555718,555718,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,2020,12,31,23,59

In [13]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

Index(['merchant', 'category', 'first', 'last', 'gender', 'street', 'city',
       'state', 'job', 'dob', 'trans_num'],
      dtype='object')

In [14]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

In [15]:
for column in categorical_columns:
    unique_values = df[column].unique()
    print(f"Unique values in '{column}': {unique_values}")

Unique values in 'merchant': [319 591 611 222 292 126 526 500 201 315 170 197 100  34 398 662 252 369
 437 489 109 621 646 656 378 258 366 154 382 296 164 689 451 402 551 264
  81 506 435 496 167 112  15 333 683  10 180  89  56 145 248 132 449 461
 457  28 536  45 663   5 484 220 690 679  38 310 174 561 209 199 144 213
 657  23 485 368 615 619 348 547 520 599 469 262  85 313 400 320 492 207
  14 257 675  76 179  33 515 452 557 490 571  46 531 314 433  67 226  74
 187 409  41   1 165 391 191 596 111 323 113 644  84 151 671 544 576 448
  13 388  22 456  61 460 104 362 139 660 541 123 312 421 651 136 392 546
   8 565 629 253 148 234 397 161 343 384 552  54 636 668 190 633 558 672
 420  75 614 540 171 317 102 574 512 529 418 125 192  95 532 471 188  69
 649 124 510 628 538 624   3 587 603  50 122 685 160 617 237 155 263 228
 277 283 606 686 385 350 195 486 265 601  82 501 438 502 256 577  66 143
 128 203 297 653 339 413 318 645 254 282 210 211 430  16 580 353  35 364
 383 236 412 316 344 573 240 221 305 445 509  98 101 670 482 519 238 373
 425 477 684 114 453 193   7 356 569 661 295 495 403 205 654 387 337  60
 528 266 648 491 579 669 166 467 175 288 455 404 131 284 487 562 169 598
 429 674 525 680 483 349 581  70 507 493 159 408 676 626 152 286 294   9
 652 473 105 374 150 524 556 465  48 219 326 375 658  93 440 655 278 250
 216 499   2 595 331 380  91 202 311 594 616 116 640  17 251 235 692 134
  78 168 642 184 367 261 612 393 593 687  30 396 249  11 185 667 279  72
  71 138 224 417 637 106  31 638 275  52 198 178 379 223  42 225 289 566
 659 338 341 133  97  37 149 447 322 376 115  44 458 274  53 287 233  83
 371 424 563 163 505 414 604 189 141 620 504 361 230 575  27 630 215   0
 390   6 127 370  40  80 586 517 335 481  32 334 306 583 244 346 480  68
 564 639 476 516 537 643 555 441  62 129  39 553 554 618  63 204 411 442
 567  59 176 419 665 545 156 246 200  26 682 304 470 121 673  90 276 327
 423  36 182 641 543 214 422 450 454 666 340 521  49 431 307 472  57 627
 406  20 401 523 592 462 260 634 568 503  19 527 386 243 259 416  47  18
 508  51 181 270 427 582 560 300 647 488 559 302 363 588 602 497 608 549
 407 271 153 439 428 570 172 466 381 459 446 479  94 268 365 426 691 610
 298 613 463  24 157 173 299 332 217  25 394 325 352 399 117 533 321 309
 474 590 354 232 444 272 607 269 110 534  55 147 625 308 622 183 345 137
 267 194 107 623 120 436 360  99 550 415 301  87 206  86 494 162 227 281
 273 632 395 290 336 498 358 142 229 572 434 177 522 600 239  29 372 539
 464 688 681 635 535 130 241 518 389 530 650 678 359 212 293  77   4  96
 208 597 329 119 664 478 103  65 285 158  88 548 330 146 242 443 118 609
  92  73 605 468 328  12 677 347  64 324 357 355  21 231  43 631 245 342
 513 196 280 135 186 542 303 140 589  79 351 475 584 578 291 585 255 514
 511 377 432  58 218 247 405 108 410]
Unique values in 'category': [10  5  9 13  7 12  1  6  0 11  8  4  2  3]
Unique values in 'first': [151 163  24  42 247  85 189 256  86 280 215 231 337  67  61 207 126 287
 297  68 265 197 315  70 186 224 119  84 216 200 145 159 340 154  15  82
 213 153 281  10 142 173  25 187  45 156  17 176   1 167 311 241   8 174
 194 196 272  36 225 309  30 212 288 238  29 107 300 331  49 148 316 122
 334 326 172 221 230  55 155  38 242 128  11 208  13 222  26 170  93 235
 214 157 140 261 185 179 228 188 336 150 262 312 171 223 100  95 298  12
 237 210 183 322 239 268 165 253 115 169  34 127 301 243 254  78 324  16
   2 282 118  43  62 180  63 302  79 308  41 279 218 283 236 202 317 133
 144  31  87 318 329 319 330  27 108 117 105 130  19 325  46   3 299  56
 233 160 110  94 143 177 291 266 161 219  14 211  64 114 250 195  53   9
 190 205 139  99   0  58 285  90 162 263 106 134 234 206  44 129  66 146
 295 332 244 102  89 310 111 199  91 313  74 123 141 252 270 147   6 113
 264   4 135 137 192 217  75  97 339 248  76  40 251 193  21 320 314  33
 245 201 293 338 260 327  96 277 267 166  37 333 182 109 274  54  22  65
 164   5 132 278 158 152 191 232 178  77 229  39 276 289  32 269 328  72
 271 181   7 255  51 204 125  81 209  60 124 296 273 112  88  18  50 246
 168  80 284 275 240 220 259 257  57 136  20 121  69 103  47 138 149 203
 101 258  83  59 306 226 307  52 175 290  28  98  23 198 292 303 304 323
 104 120 305 227  35 286  73 184 335 294  71 321 131  92  48 116 249]
Unique values in 'last': [115 457 249 261 120 409 119 121 313 213 127 283 415 455 241 294 417  90
 169 430 217  81 175  14 197 258 382 226 434  55 376 149 351  62 108 218
   5  45 273 462 150 397 245 453 383 398  99  76 161  41 360 302  46 219
 194 333 381 404  58 451  12 187 419 363   7 236 364  63 460 282 366 188
 257 440 356  91 286 439  35 446 464 330 118 308 289 340  44 172 347 244
 281 146 237 271 463 160 251 265  29 274 329  42  34 300 205 148 123  48
 227 424 137 414  59 422 105 103   0 114 327 402 117 407 418 201  71 428
  53 435 466 299 429  52  19 390 301 234 147 184 183 406 272 180 354 348
 225  11 295   3 336 377 240 176 467  33  13 412 292 345 124 109 450 328
 357 392 173 432  92   8  17 166  27 130 276 264 436  82 263   1  39 164
 138 247 287   2 145 156  87 325 141 307 158  74 443 465 131 174 100 224
 178  25 288 243 373 211 216 403  73 378 209 189 200 255  79 128 367 312
 400 163 203 405 101 135 113 168 447  61  36 358 355 322  95 372 342  20
 401 326  57 448 259 266 191  93 387 125 112  24 420 270 296 310 256 433
 139 246 339 275 321  10 196  60 361 230  66 384 186 210  26 416 170 394
  37 154 395 229 192 452 233 111 238  85 388 279  98  80 267 423 349 362
  75 248 445 375 220 242 441 331 102 159 306 298 104 221 324 235 338 122
 285 368 469 204 468 106 458  18 162 353  23 193 369  38  89 232 343 215
 303 315 411  65 311 207 389 408  16  50 284 305 132 431  32 334 374 143
 421 202 254 151 133 269 199 314  84 212 208 239 425  77 277 260 385  30
 262  28   9 370  64 252 426 320 179   6 206  31 379 231 427 228 107 413
 280 171 399  78 459 335 152 341 198  56  54  88 391 304  68 365 253 319
 116 157 136 110 153 293  49 346 410  69 371 332 177 134 454 222 297  15
  67 442   4  47 290 396 250 309 316 352 291 195  96 223  83 181 167 182
 393 268 438 337  72 190  40 140 444 456 470 278 317 165 461 155 129 323
 214 386 126  94 437 142  51 344  70 185  86  43 350  97 318 449 144  21
 380  22 359]
Unique values in 'gender': [1 0]
Unique values in 'street': [341 354 865 320 548 727   9 340 400 751 415 439 225 909 394 488 788  25
 620 424 866 191 275 167 248 484 485 683 623  22 523 230 377 914 453 256
 162  54 147 652 486 399 763 112 234 848 807 369 631 175 405 333 184 468
 241 389 321 657 476 769 684 407  43 208 823 911 293 255 687  17 384 678
 329 474 614 723 679 402 161  41 224 452  59 262 463 398 328 419 910 883
 395 557 381 583 814 794 457 617 671 136 416 460 904 646 304 278 601 423
 682  98 774 314 434 800 767 726 636 146 739  84 102 199 735 886 762 362
 833 633 864 274 505  21  34 326 387 622 540 539 507 754 420 132  67 771
 918  13 163 356 529  97 566 473 602  51 159 165 881  93 154 743 332  12
 527 637 217 880 782 233  58 118 542 565 240 265 260 641   0 802 144  66
 464 237 922 675 203 219 889 662 107 712 172 525  11 673 919 491 414  70
 150 477 780 677 664 268   2 902 149 129 380 806 307 436 524  62 373 140
 765 156 879  47 590 166  94 295 745 561 229 744 878 130 298 355 665 267
 232 178 867 450 519 446 417 537 231 391 734 768 343 245 740 342 778 315
  65  46 171 809 435 717 411 253 580 197 610 828 784 628 345 569 547 810
 905 777 808 612 813 556 249 621  29 832 368 408 284 173 836 874 592 202
 350  24  33 760 303 654 582 849 724 720 186 706 627 674 309 870 521 901
 893 121 732  90 300 647 515 286 390 512 169  88 696 670 885 896 182 541
 273 530 312 658 648 371 522 513 845 611 667 859 433 365  31 920 710 770
  85 533 668 703 344 151 176 538 663 449 215 672 271 838 518 817 404 282
 270 868 669  30 462 563 841 837 753 844 792 908 376  83 188 401 598 594
 209 882 578 145 555 528 564 722 821 884   3  68 574  48  42 600 831 584
 639 689 615 119 581 907 366 348 310 644 660 579 289 497 516 211 536 396
 681 635 454 221 699 285  27 204 495 142 839 122 318 820 595 105 705 106
 403 894 544 200 276 305 776 338  38 410 455 461 738 861 194 266 499 379
 775 686 128 819 101 500 471 749 656 131 752 251 805 179 177 242 198 227
 708 746 655  44 827 160 605 651 139 103 277 374 826 218 799 193 475 873
 351  92 593 469 653 143 392 465  36  45 877 510 123 261 481 244 903 493
 534 737 283 550  49 890 214 331 272 279 306  91  72  69 243 626 793 252
 630 718 498 174  32  64  81 707  77  37 736  99 367   8 288  19 334   5
 489 301  86 695 503 137 385 604  52 290 688 352  79 818 386 923 634 719
  87 791  16  76 661 853 212 871 700 496 316 425 258 645 382 571 228 153
 895  82 773 447 361 680 418 511 100 138 359 372 133 570 842 210  96 917
 875 504 323 619 891 742  15 764 640 721 857 789 478 126 755 618 135 756
 554 685 158 114 815  73 586 456 702 109 250 308 834 235 185 676 508 816
 472 222 183 589 629 790 854 459 906 294 697 319 364 108 181 358 916  55
 116 492 280   1 363 597 397  50 157 650 795 575 716 111 325 772 897 856
 855 691 624 613 480 783 317 787 606 406 750 168 426 840 829 846 758 567
 422 587 779 440 164 591 572 330 375 192 421 324 577 291 847  80 843 872
 801 127 694 322 302 915 207 216 692 187 532 553 599 296 337 588 514 490
 830 796 709 520 134 195 213 494 370 444 155  26 427 335 336   7 607 346
 888 825 223  10 741 388 236   4 412 698 549 850 445 803 759  89 442 552
 666 531 347 443 761 292 148 467 643 900 205 378 535 110 487 104 596 632
  63  74  78 437 353 913 517 239 526 247  18 757 246  14  40 560 585 297
 124 117 196 811 152 616 254 393 562 413 543 797 470 190 180 798 608 546
 313 642 483  71  28 141 466 257 281 431 432 299 766 714  61  95  20 311
 238 482 887  39 409 206 327 360 220 786 715 170 876 728 869 451 383 912
 448 730 438 339 603 357 226 479 785  56 269  57 559 638 545 731 349 558
  35 781 704 804 259 429 125 287 441 201 921 729  23 458 898 812 711 690
 860 573 863 822 263  60 264 649 120 824 501 862 858 659 892 551  53 835
 725 852  75 748 713 509 693 189 625 428 733 576 899 851 701 430 502 747
 113 609   6 506 568 115]
Unique values in 'city': [157  16  61 764 247  90 117 725 503 624 824 258 441 658 371 196 383 280
 676 139  12 155 289 765 275 183 721 418 532 533 602 609  62  42 447 719
 316 262  71 569  50 684 723 467 631 431 774 746 566 642  97 253 661 619
 281 763 796 143  98 747 274 346 657 351 257 773 717 230  52 674 234 530
 682 150 665 128 160 751 670 576 232 492 545 514 727 120 161 706 527 518
 191 179 207 663 775 605 549 311 500 241 828  18  13 638 519 610 601 400
 606 417 395 217 475  82 181 238 707   8 805 555 171  25 240 261 325 749
 225 403 757 337  51 193 635 543 552 401 163 482 305 779 736 718 521 187
 745  22 726 669 836 326 668  15 422 322 761 709 473  32 424 461 625 290
 127 744 125 781 839 188 165 497  74 579 256 362 369 399 423 729 720 780
 506  29 529 615 542 843 464 754 387  65 449 244 332 616 341 339 124 376
 108 300 748 297 795 814 845 126 756 347 343 567 848 123  23 304 694 319
 455 162 342 302 767 277 495 237 416 733 489 106 429   0 180 210 239 650
 415 478 255 373 144 595 231 434 224 687 390  59 103 194 428 575 686 386
  14  48  49 562 458 243 772 820 777  87   9 398 823 294 704 481 368 433
 655 637 440 534 282  81 140 285 771 675 498 837 570 134 148 540 463 523
 653 363 379 664 524 367 784 141 414 509 806 381 384 782 699 842 618 138
 320 807 119 135 202 397 692 802 229 223 328 271 412 154 270 776 690   3
 597 846  44 513 813  53 825 421 472 662 291 393 101 476 536 389  92 102
 284 203 438 113   5 810 644 693 293 483 169 248 200 361 708 454  11 471
 829 214 136 313 564 149 582 641 614  88  58 218 591  96  67 334 617 689
 834 743 737 636 786 205 671 330  68 333 301 374 204 526  63 520  76 439
 819 167 815 511 715 735 613 114 488 444 539  38 279 685 800 809 323 632
 201 830 252 321 335  77 546 287 357 110 432 435 370 394 268  37  28 724
 264 705 265 405 105 354 314 352 331 580 628 818 673 792 568  36 516 817
  27 406 770 174 206 356 227 310 121 278 565 535 651 116 358 640 220 378
 152 453 760 778 827 308 450 170  40 499 581 269 794 755 577 164 480  56
 486 758  31 296 553 803   1 184 377 233 115 821 507 151 437 259 607 835
 111 408 186 173 811 355 652 228  35 178 612 608  26  95 404 192 714 118
 838  79 213 742 753 713 766 832 677  83 251 558 254  45 288 679 236  89
 360 250 375 198 470  39  85 272 739 317 812  54 599 695 226 681 366 318
 799 410 611 702 572 145 446 336 649 142 666 752 112 235 104 190 592 133
 730 559 586 175 541 522 276 219 847 621  46 496  80 307 490 245 711 551
 309 768 411 122  93 350 215 266 494 413 359 216 630 646 402 647 785 598
 508  72 691  69 212 493 678 531 345 409 547  34 469 833 634  75 465 260
 131 249 804 557 156 100 645 840 738 629 703 445  91  64 146 197 273   4
 769 452 544  55 246 740 831  94 563 515 789 517 129 348 459 622 327 783
 560   6 420 654 344 382 816  43 731 222  47 710 680 474 107 158 182 456
 159 457 583  19  86 283 189  33 790 822 593 485 793  73 340 364 166 571
 443 550 797  60 329 299 659 660 561 556 798 185 109 697  66 620 734 132
 153 479 512 525  57 315 385 487 242 722  84  10 460 603   7 430 574 762
 548 306  17 380 484 442 578 787 623 841  99 791 688  78 312 633 292 176
 338 267 588 683  21 425 436 172 303 604 672 448 502 510 585 221 600 594
 537 353 801 177 462 587 263 407 501 466 759 426  41 627 324 589  30 554
 667 696 728 538 365 712 388 468 396  70   2 427 286 130 209 844 656 528
 788 349 590 716 195 199  20 643 211 477 451 147 208 491 372  24 639 584
 505 808 573 732 741 137 596 626 750 648 295 419 391 392 504 700 698 826
 298 168 701]
Unique values in 'state': [39 43 33  8 21  4 40 37 42 16 49  1 17  9  5 34 47 45  2 30 11 19 24 15
 13 23 20 41  7  3 25 22 35 46 48 31 18 28 44 12 36 14 26 29 27  6 32 10
 38  0]
Unique values in 'job': [275 392 259 407 196 361 455 124  13  41 320 194 316  51 274  88 460 375
 428 145 339 291 277 405 252  52 394 106 396  39 419 256  95 389  85 258
 135  60 294 116 180 148 186 475 171 348 137 406 243 264 395 433 338  15
 203 202 279 321  11 466 292 298 197 456 308 408  91  76 158 113  21 141
 378   3 260 354  70 211 184  77 415 114 430  45 206 140 176 144 333 293
 299 246 451  31 350 183 134 164 247 129 362 352 101 422  47  23 240 157
 218 311 190 104 119 399 187 130 236  48  86 341 193 442 436  98 139 390
 317 198 222  69  66  61 235 174 115 385 170  50  53 425  99 181   2 404
 347 473 238 310 191 409 108  26  63  97 248 102  94 313 423 391 255 366
 465 244  56 249 162  33 270 441 471 372 462 284 215 332 107 199 179 166
 461 265 257 133 328  57 432  12 302   1 336 476  25 403 371 458  44 254
 364   5 285 397   8 272  72 276  32  80 297 156 288 402 414 207 359 221
 195  65 467 398 346 188 373 286 464  73 450 326 318  35 439 444 388 105
 329 420 365 239 434 327 435 309 172 230 379  24  18 117 153 334 100 412
  27 418 446  42 154 103 474 233 112 342  58 210 340 410 319 357  49 122
  40  81 429 421  28 358 109 213 143 400 214 459 250 315 468 369 204 452
 128 227 208 453 268 325  92 142  46 182 449 110 401  89   9 123 217 262
 201  34 323 440  67 205 335  93 232  74 149 263   0  90 383 438 147 296
  82 384 111 448 374 242 355 380 253 251 314 225 463 337 377 322 168 155
 220 267 343  22 426 228 271 126 344  29 138  96 445 393 370 192 287 278
 472 303  87 189  55 443 416 212 241 301  84 353 387 161 125 118 216 290
 300 363 269 234  19 386 360  20 175 150 331 159  68  71 469 330 231 283
 356 282 312 266 127 345  10 427 324 280  16  54 295 367 237 245   7 305
 454 261  37  43  78  83 477 200 381 289 437 120 447  79 173 209 121  38
  64 368 424 223 382 165 185 151   4  75 376  59 178 163 349 136 229 219
 131 146 470  17 152 177  14 160  30 273 224 457 351 306 431 132 169 226
 281  62   6 304 413 417  36 167 307 411]
Unique values in 'dob': [376 760 421 718 177 796 130 446 475 189 856 524 541  51 437 734 706 802
 553 867 872 799 439 870 671 795 206 387 112 209  20 494 313 499 305 213
 842 409 588 396 542 520 503 253  79 465 582 699 830 497 498  17 743  34
 819 317 685 581 886 726 622 877 654 447 675 303 883 596 518 672 372 555
 746 748 419 751 656 366 895 115 682 566 688 492 363 413  53 335 704 732
 811 332 678 438 321 450 592  91 738  87 676 803 634 117 557 424 906 142
 608 543 626 414 427 866 505 454 418 652 135 479 577 349 309 176 468 615
 453 578 389 607 125 858 865 873 904 160 890 249 857 791  69 273 768 844
 684 422 461 178 203 511 627  99 508 152   0 730 134 567 295 244 513 812
 698 319 431 800 516 897 340 896 774 851 155 124 240 133 644 861 888 408
 907 868 782 126 252 733 665 237 225 887 162 580 882 707 745 575 420 889
 741 333 119 484 390 727 869 780   2 483 200 551 573 440 423 894 779 898
 342 679 658  77 643 472 449 778 338 636 452 659 908 208 238 717 838 853
 443 487 165 815 257 610 339 695 594 538 677 849 397 764 620 813 105 254
 181 510 572 304 530 559 859 880 901 602 457 810 274 359 536 769 635 512
 477 560 459 481 167 604 568 705 101 891 786 828 455 350 289 489 476 434
 576 881 109 623 790 478 680 325  35 818 458 716 797 589 490  85 326 552
 550 752 532 640 448 683 843 515 770 529 132  45 702 749 597 831 621  46
 700 864 316 122 445  33 647 689  40 211  70 900 411 154 611 841 451 801
 197 776 375 563 216 331 429 207 554 500 193 277 141 297 285  56 485 278
 860 394  92 661 703 194 352 144 638  14 758 595 879 501 121 131 265 514
 648 341 740 386 655 214 280 723 199 777 248 817 587 283 708 847 226 583
 247 719 657 168 613 650 875  71 381 909 766 686 820 170 903 839 329 246
 664 755 172 630 355 284 374 756  75 527 407 110 242 809  19 617 279 220
 714 885 343 315 104 603 722 259 605 228 798 585  88 217 308 205  44 645
 436 523 128 401 653 593 840 111 833 806  98 231 692 834 697 639 306 462
 822  84 480 762 174 467 258 496 466 691 549 669  52 899 666 787  89 100
 275 380 521 687 663 825 369 721 433 731 788 540 668 539 113 456 893 371
 710   3 517 821 646 296 735 773  23 488 201  38 147  21 261 362 547 696
 234 761 357 241 301 807  24 846 535 537 102 827 482 651 614 464 412 694
 504 586 794 173 753 724 239 344 190 163 681 701 486 737 765 631 660 402
 219  76 533 157 416 507 299   7 606 863 690 649 712 399 292 848  18 360
   8 525 805 432 383 495 222 739 471 271 785 744   1  96 637 792 444 108
 251  62 403 609 564 185  86 392 441  37 151 378 674  74  11 569 391 829
 406 816 186 348 633  13 823 324 584 426  60  42 470 118 286 191 835 227
 143 667 460 233 116 729 837 619 180 662 713 612 346  32  25 571 562 187
 491 354 140 415 245 235  12 182 767 287 556 428 473 546 814 293 400 548
  78 164 310 327 107 852 845 269 590 218 565 832 138 307 709 884  72 601
 356 855 379 670 230 711 742 693 502 169 171 212  36 156 793 345 720 322
 150 526 262 148 509 824 750  10  73 382 282 264 417 103 302 506  66 243
  22  58 531 232 368 558  83  80 405 628 808 361 106 202 139 192 196 256
  43 905  59 358  41 123 629 850 334  54  63 784 365 871 624 522 330 367
 272 757  47  95 291 673 290 377 599 600  68 221 195 570 114  16 300 298
 166  49 519  39 270 642 747 410 255 430 276  94 474  67 395 137 876  81
 353 323 370 127 336  28 763  31 874 210 183 347 229 783 175  26 281 260
  15 320  64 337  57 250 145 771 591 442   5   9 618 179   4 854 328  93
  55 574 267 158 311 736 425 728 625 263 632 198  61 804 715 528 159  50
 772 146 836   6 641 266 598 314 544  97 789 120  30 435 775 579 616 754
 318 236 534 385 469  90 561 215 725  29 136  65 149 153 393 351 398 826
 781 493 294 759 161 463 224 312 188 364 129 545 268  82 204  27 388 892
 288 384 184 902 373  48 878 404 862 223]
Unique values in 'trans_num': [ 98699 108785 433979 ... 235088  43546  50595]

In [16]:
# Separate features (X) and target (y)
X = df.drop(columns=['is_fraud'])  # Features
y = df['is_fraud']  # Target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the feature matrix
scaler = StandardScaler()
X_train_standardized = scaler.fit_transform(X_train)
X_test_standardized = scaler.transform(X_test)

In [17]:
X = df.drop(columns=['is_fraud'])  # Assuming 'is_fraud' is the target variable
y = df['is_fraud']

In [18]:
X

,Unnamed: 0,cc_num,merchant,category,amt,first,last,gender,street,city,...,dob,trans_num,unix_time,merch_lat,merch_long,year,month,day,hour,minute
0,0,2291163933867244,319,10,2.86,151,115,1,341,157,...,376,98699,1371816865,33.986391,-81.200714,2020,6,21,12,14
1,1,3573030041201292,591,10,29.84,163,457,0,354,16,...,760,108785,1371816873,39.450498,-109.960431,2020,6,21,12,14
2,2,3598215285024754,611,5,41.28,24,249,0,865,61,...,421,433979,1371816893,40.495810,-74.196111,2020,6,21,12,14
3,3,3591919803438423,222,9,60.05,42,457,1,320,764,...,718,71993,1371816915,28.812398,-80.883061,2020,6,21,12,15
4,4,3526826139003047,292,13,3.19,247,261,1,548,247,...,177,190585,1371816917,44.959148,-85.884734,2020,6,21,12,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,30560609640617,507,5,43.77,235,315,1,531,443,...,334,336391,1388534347,39.946837,-91.333331,2020,12,31,23,59
555715,555715,3556613125071656,264,7,111.84,171,424,1,540,401,...,890,70372,1388534349,29.661049,-96.186633,2020,12,31,23,59
555716,555716,6011724471098086,496,7,86.88,18,239,0,126,104,...,609,235088,1388534355,46.658340,-119.715054,2020,12,31,23,59
555717,555717,4079773899158,75,13,7.99,111,342,1,663,476,...,331,43546,1388534364,44.470525,-117.080888,2020,12,31,23,59
555718,555718,4170689372027579,125,0,38.13,280,145,1,778,224,...,813,50595,1388534374,36.210097,-97.036372,2020,12,31,23,59

In [19]:
y

0         0
1         0
2         0
3         0
4         0
         ..
555714    0
555715    0
555716    0
555717    0
555718    0
Name: is_fraud, Length: 555719, dtype: int64

In [20]:
#Feature Scaling â€“ Standardization (To standardize Salary)
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
X= sc_x.fit_transform(X)
print(X)

[[-1.73204769 -0.31725171 -0.11966343 ...  0.5065263  -0.11878896
  -0.89397942]
 [-1.73204146 -0.31627306  1.23165562 ...  0.5065263  -0.11878896
  -0.89397942]
 [-1.73203522 -0.31625383  1.33101731 ...  0.5065263  -0.11878896
  -0.89397942]
 ...
 [ 1.73203522 -0.31441123  0.75968757 ...  1.6231831   1.49626514
   1.70110652]
 [ 1.73204146 -0.31899779 -1.3318761  ...  1.6231831   1.49626514
   1.70110652]
 [ 1.73204769 -0.31581678 -1.08347186 ...  1.6231831   1.49626514
   1.70110652]]

In [21]:
X

array([[-1.73204769, -0.31725171, -0.11966343, ...,  0.5065263 ,
        -0.11878896, -0.89397942],
       [-1.73204146, -0.31627306,  1.23165562, ...,  0.5065263 ,
        -0.11878896, -0.89397942],
       [-1.73203522, -0.31625383,  1.33101731, ...,  0.5065263 ,
        -0.11878896, -0.89397942],
       ...,
       [ 1.73203522, -0.31441123,  0.75968757, ...,  1.6231831 ,
         1.49626514,  1.70110652],
       [ 1.73204146, -0.31899779, -1.3318761 , ...,  1.6231831 ,
         1.49626514,  1.70110652],
       [ 1.73204769, -0.31581678, -1.08347186, ...,  1.6231831 ,
         1.49626514,  1.70110652]])

In [22]:
#Train Test Split Data 

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2)
print (X.shape)
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(555719, 26)
(444575, 26)
(111144, 26)
(444575,)
(111144,)

In [23]:
#Create Model 

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
print (lr)

LogisticRegression(max_iter=1000)

In [24]:
#Predict the Result (Test Data Set) 
y_pred= lr.predict(X_test)
print (y_pred)

[0 0 0 ... 0 0 0]

In [25]:
#Display y_test 
print (y_test)

494624    0
360122    0
488781    0
348697    0
415569    0
         ..
157727    0
547586    0
108956    0
272276    0
343323    0
Name: is_fraud, Length: 111144, dtype: int64

In [26]:
#Display Test and Prediction 
# Reset the indices of y_test and y_pred
y_test = y_test.reset_index(drop=True)
y_pred = pd.Series(y_pred)

# Create the DataFrame for display
df_result = pd.DataFrame({'Y_Test': y_test, 'Prediction': y_pred})
print(df_result.head(50))

    Y_Test  Prediction
0        0           0
1        0           0
2        0           0
3        0           0
4        0           0
5        0           0
6        0           0
7        0           0
8        0           0
9        0           0
10       0           0
11       0           0
12       0           0
13       0           0
14       0           0
15       0           0
16       0           0
17       0           0
18       0           0
19       0           0
20       0           0
21       0           0
22       0           0
23       0           0
24       0           0
25       0           0
26       0           0
27       0           0
28       0           0
29       0           0
30       0           0
31       0           0
32       0           0
33       0           0
34       0           0
35       0           0
36       0           0
37       0           0
38       0           0
39       0           0
40       0           0
41       0           0
42       0           0
43       0           0
44       0           0
45       0           0
46       0           0
47       0           0
48       0           0
49       0           0

In [27]:
#Display Accuracy 
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.9960771611602965

In [28]:
#Display Confusion Matrix 

from sklearn.metrics import confusion_matrix 
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[110708     24]
 [   412      0]]

In [29]:
#Display Classification Report 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred,zero_division=0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    110732
           1       0.00      0.00      0.00       412

    accuracy                           1.00    111144
   macro avg       0.50      0.50      0.50    111144
weighted avg       0.99      1.00      0.99    111144

In [30]:
#Prediction for Complete Data set  
y_pred= lr.predict(X)
print (y_pred)

[0 0 0 ... 0 0 0]

In [31]:
#Display Accuracy 
from sklearn.metrics import accuracy_score
print (accuracy_score (y,y_pred))

0.9958738139239436

In [32]:
#Display Confusion Matrix 

from sklearn.metrics import confusion_matrix 
cm = confusion_matrix (y,y_pred)
print (cm)

[[553426    148]
 [  2145      0]]

In [33]:
#Display Classification Report 
from sklearn.metrics import classification_report
print(classification_report (y,y_pred,zero_division = 0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.00      0.00      0.00      2145

    accuracy                           1.00    555719
   macro avg       0.50      0.50      0.50    555719
weighted avg       0.99      1.00      0.99    555719

In [34]:
df

,Unnamed: 0,cc_num,merchant,category,amt,first,last,gender,street,city,...,trans_num,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,minute
0,0,2291163933867244,319,10,2.86,151,115,1,341,157,...,98699,1371816865,33.986391,-81.200714,0,2020,6,21,12,14
1,1,3573030041201292,591,10,29.84,163,457,0,354,16,...,108785,1371816873,39.450498,-109.960431,0,2020,6,21,12,14
2,2,3598215285024754,611,5,41.28,24,249,0,865,61,...,433979,1371816893,40.495810,-74.196111,0,2020,6,21,12,14
3,3,3591919803438423,222,9,60.05,42,457,1,320,764,...,71993,1371816915,28.812398,-80.883061,0,2020,6,21,12,15
4,4,3526826139003047,292,13,3.19,247,261,1,548,247,...,190585,1371816917,44.959148,-85.884734,0,2020,6,21,12,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,30560609640617,507,5,43.77,235,315,1,531,443,...,336391,1388534347,39.946837,-91.333331,0,2020,12,31,23,59
555715,555715,3556613125071656,264,7,111.84,171,424,1,540,401,...,70372,1388534349,29.661049,-96.186633,0,2020,12,31,23,59
555716,555716,6011724471098086,496,7,86.88,18,239,0,126,104,...,235088,1388534355,46.658340,-119.715054,0,2020,12,31,23,59
555717,555717,4079773899158,75,13,7.99,111,342,1,663,476,...,43546,1388534364,44.470525,-117.080888,0,2020,12,31,23,59
555718,555718,4170689372027579,125,0,38.13,280,145,1,778,224,...,50595,1388534374,36.210097,-97.036372,0,2020,12,31,23,59